Emulate behaviour of `haproxy-systemd-wrapper`. (#390)
This also drops the `HAPROXY_RELOAD_SIGTERM_DELAY` param.

For reference, see:
http://git.haproxy.org/?p=haproxy.git;a=blob;f=src/haproxy-systemd-wrapper.c;h=f6a9c852b277b5f193d6a952119a149b4cfe3e8b;hb=HEAD

diff --git a/service/haproxy/run b/service/haproxy/run
--- a/service/haproxy/run
+++ b/service/haproxy/run
@@ -33,9 +33,10 @@ reload() {
 
     # Trigger reload
     LATEST_HAPROXY_PID=$(cat $PIDFILE)
-    haproxy -p $PIDFILE -f /marathon-lb/haproxy.cfg -D -sf $LATEST_HAPROXY_PID 200>&-
-    if [ -n "${HAPROXY_RELOAD_SIGTERM_DELAY-}" ]; then
-      sleep $HAPROXY_RELOAD_SIGTERM_DELAY && kill $LATEST_HAPROXY_PID 200>&- 2>/dev/null &
+    /marathon-lb/haproxy_wrapper.py `which haproxy` -p $PIDFILE -f /marathon-lb/haproxy.cfg -sf $LATEST_HAPROXY_PID 200>&-
+    local exit_code=$?
+    if [ $exit_code -ne 0 ]; then
+      echo "HAProxy reload failed" 1>&2
     fi
 
     # Remove the firewall rules
