Update Marathon-LB version v1.11.3 (#17)
* Change README.md (#487)

Proposed change to README.md to warn users about use of zdd.py on a production environment.

* Add container syslogd support and fix 'Waiting for Pids' race condition (#505)

* Add additional debug logs in reload
* Adding syslog support
* Make syslogd and retry reload configurable
* Update documentation
* Make infinite retries optional, run syslogd with runsvdir

* Update base container to resolve CVE-2017-12424 (#506)

* Update base container to resolve CVE-2017-12424

Updated base container to debian:buster to resolve this attack vector.
https://security-tracker.debian.org/tracker/CVE-2017-12424

* delete unnecessary swp file

* Fix grammar in tini section of README.md (#442)

* exclude bad apps from generated config (#481)

exclude bad apps from generated config

* Fix reconnect logging and timing depending on error type (#523)

* Fix reconnect logging and timing depending on error type

* cleanup flake8 errors

* add missing build-essential

* start at most one thread and close connection when reconnecting

* Filter events on server side, in order to decrease load on Marathon (#541)

* Filter events on server side, in order to decrease load on Marathon
* Use lightweight Marathon events.

* Update official Marathon-LB version to 1.11.3

* Fix error with bash run script, percentage symbol was not escaped

diff --git a/service/haproxy/run b/service/haproxy/run
--- a/service/haproxy/run
+++ b/service/haproxy/run
@@ -2,6 +2,17 @@
 exec 2>&1
 export PIDFILE="/tmp/haproxy.pid"
 
+LOG_PREFIX="$(pwd) $0"
+log() {
+    logline="[$LOG_PREFIX] $1\n"
+    printf "$logline" >&1
+}
+log_error() {
+    logline="[$LOG_PREFIX] $1\n"
+    printf "$logline" >&1
+    printf "$logline" >&2
+}
+
 addFirewallRules() {
   IFS=',' read -ra ADDR <<< "$PORTS"
   for i in "${ADDR[@]}"; do
@@ -17,33 +28,44 @@ removeFirewallRules() {
 }
 
 reload() {
-  echo "Reloading haproxy"
+  log "Reloading haproxy"
 
   (
     flock 200
 
-    # Begin to drop SYN packets with firewall rules
+    log "Dropping SYN packets with addFirewallRules"
     addFirewallRules
 
     # Wait to settle
     sleep 0.1
+    log "addFirewallRules done"
 
-    # Save the current HAProxy state
+    log "Saving the current HAProxy state"
     socat /var/run/haproxy/socket - <<< "show servers state" > /var/state/haproxy/global
+    log "Done saving the current HAProxy state"
 
     # Trigger reload
     LATEST_HAPROXY_PID=$(cat $PIDFILE)
-    /marathon-lb/haproxy_wrapper.py `which haproxy` -D -p $PIDFILE -f /marathon-lb/haproxy.cfg -sf $LATEST_HAPROXY_PID 200>&-
+    log "LATEST_HAPROXY_PID: [$LATEST_HAPROXY_PID]"
+
+    WHICH_HAPROXY=$(which haproxy)
+
+    log "/marathon-lb/haproxy_wrapper.py $WHICH_HAPROXY -D -p $PIDFILE -f /marathon-lb/haproxy.cfg -sf $LATEST_HAPROXY_PID 200>&-"
+    /marathon-lb/haproxy_wrapper.py $WHICH_HAPROXY -D -p $PIDFILE -f /marathon-lb/haproxy.cfg -sf $LATEST_HAPROXY_PID 200>&-
     local exit_code=$?
+    log "exit code: $exit_code"
     if [ $exit_code -ne 0 ]; then
-      echo "HAProxy reload failed" 1>&2
+      log_error "HAProxy reload failed"
     fi
 
-    # Remove the firewall rules
+    log "Removing firewall rules with removeFirewallRules"
     removeFirewallRules
+    log "removeFirewallRules done"
 
     # Need to wait 1s to prevent TCP SYN exponential backoff
     sleep 1
+
+    log "Reload finished"
   ) 200>/var/run/haproxy/lock
 }
 
